#!/usr/bin/env python
'''
structinfo_generator scans C header files for struct definitions
and generates the following functions for all struct members:
1. getters: <member typedef> get_<struct name>_<member name>(void *ptr);
2. sizeof: size_t sizeof_<struct_name>(void);
3. offsetof: size_t offsetof_<struct_name>_<member name>(void); 
'''
# Author: Pearu Peterson
# Created: July 2018

from xndtools import structinfo_generator

def show_description(args):
    print(__doc__)
    print('For detailed usage, run:\n\n  {} -h\n'.format(__file__))

def main():
    import argparse
    parser = argparse.ArgumentParser(description = __doc__,
                                     prog = 'structinfo_generator')
    parser.add_argument('--version', action='version', version='%(prog)s 1.0')
    parser.set_defaults(func=show_description)

    parser.add_argument('-I', '--include-dir',
                        default=[], action='append',
                        help='Specify include directory')
    parser.add_argument('include',
                        help = 'Specify header file to be scanned for struct definitions')
    parser.add_argument('-o','--output',
                        help = 'Specify path to C source file where the functions will be generated'
    )
    parser.set_defaults(func=structinfo_generator.generate)
    args = parser.parse_args()
    args.func(args)
    
if __name__ == '__main__':
    main()
